# Generated by Django 5.2.17 on 2026-08-20 05:05

import alerts.services.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("arkl", "0002_arklresult_exposure_concentration_mg_m3_and_more"),
        ("devices", "0001_initial"),
        ("exposure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concentration_ppm",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("environmental_level", models.PositiveSmallIntegerField()),
                ("environmental_status", models.CharField(max_length=64)),
                (
                    "environmental_severity",
                    models.CharField(
                        choices=[
                            ("NORMAL", "NORMAL"),
                            ("CAUTION", "CAUTION"),
                            ("WARNING", "WARNING"),
                            ("DANGER", "DANGER"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rq", models.DecimalField(decimal_places=12, max_digits=24)),
                ("risk_interpretation", models.CharField(max_length=32)),
                ("calculation_version", models.CharField(max_length=32)),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "risk_status",
                    models.CharField(
                        choices=[
                            ("NO_ACTION_REQUIRED", "NO_ACTION_REQUIRED"),
                            ("MONITORING_REQUIRED", "MONITORING_REQUIRED"),
                            ("RISK_MANAGEMENT_REQUIRED", "RISK_MANAGEMENT_REQUIRED"),
                            ("IMMEDIATE_ACTION_REQUIRED", "IMMEDIATE_ACTION_REQUIRED"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("ACKNOWLEDGED", "ACKNOWLEDGED"),
                            ("RESOLVED", "RESOLVED"),
                        ],
                        default=alerts.services.constants.AlertLifecycleStatus["OPEN"],
                        max_length=16,
                    ),
                ),
                ("recommendation_codes", models.JSONField(default=list)),
                (
                    "alert_rule_version",
                    models.CharField(default="1.0.0-MVP", max_length=32),
                ),
                ("source_simulated", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arkl_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="arkl.arklresult",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="devices.device",
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="devices.h2sreading",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="exposure.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["worker", "status"], name="alert_worker_status_idx"
                    ),
                    models.Index(
                        fields=["device", "status"], name="alert_device_status_idx"
                    ),
                    models.Index(
                        fields=["alert_level", "status"], name="alert_level_status_idx"
                    ),
                ],
            },
        ),
    ]
