# Generated by Django 5.2.17 on 2026-08-19 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("exposure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARKLResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("REALTIME", "Realtime"),
                            ("HISTORICAL", "Historical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "concentration_ppm",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "concentration_mg_m3",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("body_weight", models.DecimalField(decimal_places=4, max_digits=10)),
                ("exposure_time", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "exposure_frequency",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "exposure_duration",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "inhalation_rate",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "averaging_time",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("intake", models.DecimalField(decimal_places=12, max_digits=24)),
                ("rfc", models.DecimalField(decimal_places=8, max_digits=14)),
                ("rq", models.DecimalField(decimal_places=12, max_digits=24)),
                ("interpretation", models.CharField(max_length=50)),
                ("calculation_version", models.CharField(max_length=30)),
                ("source_simulated", models.BooleanField(default=False)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("reading_count", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arkl_results",
                        to="devices.h2sreading",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arkl_results",
                        to="exposure.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
