# Generated by Django 5.2.17 on 2026-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arkl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arklresult",
            name="exposure_concentration_mg_m3",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="arklresult",
            name="averaging_time",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="arklresult",
            name="intake",
            field=models.DecimalField(
                blank=True, decimal_places=12, max_digits=24, null=True
            ),
        ),
    ]
