/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_accounts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_alerts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_alerts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{id}/acknowledge/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_alerts_acknowledge_partial_update"];
        trace?: never;
    };
    "/api/v1/alerts/{id}/resolve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_alerts_resolve_partial_update"];
        trace?: never;
    };
    "/api/v1/alerts/evaluate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_alerts_evaluate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arkl/historical/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate historical ARKL risk */
        post: operations["v1_arkl_historical_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arkl/realtime/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate realtime ARKL risk and evaluate alert */
        post: operations["v1_arkl_realtime_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arkl/reference/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_arkl_reference_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arkl/reference-measurements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_arkl_reference_measurements_list"];
        put?: never;
        post: operations["v1_arkl_reference_measurements_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arkl/reference-measurements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_arkl_reference_measurements_retrieve"];
        put: operations["v1_arkl_reference_measurements_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_arkl_reference_measurements_partial_update"];
        trace?: never;
    };
    "/api/v1/arkl/results/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ARKL results */
        get: operations["v1_arkl_results_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arkl/results/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve ARKL result */
        get: operations["v1_arkl_results_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_devices_list"];
        put?: never;
        post: operations["v1_devices_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_devices_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_devices_partial_update"];
        trace?: never;
    };
    "/api/v1/exposure-profiles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_exposure_profiles_list"];
        put?: never;
        post: operations["v1_exposure_profiles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exposure-profiles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_exposure_profiles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_exposure_profiles_partial_update"];
        trace?: never;
    };
    "/api/v1/me/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_me_alerts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/arkl-results/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_me_arkl_results_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/exposure/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_me_exposure_retrieve"];
        put?: never;
        post: operations["v1_me_exposure_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_me_exposure_partial_update"];
        trace?: never;
    };
    "/api/v1/me/monitoring/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_me_monitoring_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_me_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_me_profile_partial_update"];
        trace?: never;
    };
    "/api/v1/readings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_readings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_readings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/latest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_readings_latest_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/alert-summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Base class for Research endpoints.
         *
         *     ADMIN / OPERATOR / RESEARCHER:
         *         authenticated read access.
         *
         *     WORKER:
         *         denied.
         */
        get: operations["v1_research_alert_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/arkl-results/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Base class for Research endpoints.
         *
         *     ADMIN / OPERATOR / RESEARCHER:
         *         authenticated read access.
         *
         *     WORKER:
         *         denied.
         */
        get: operations["v1_research_arkl_results_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/export/arkl.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Base class for Research endpoints.
         *
         *     ADMIN / OPERATOR / RESEARCHER:
         *         authenticated read access.
         *
         *     WORKER:
         *         denied.
         */
        get: operations["v1_research_export_arkl.csv_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/exposure-summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Base class for Research endpoints.
         *
         *     ADMIN / OPERATOR / RESEARCHER:
         *         authenticated read access.
         *
         *     WORKER:
         *         denied.
         */
        get: operations["v1_research_exposure_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/h2s-summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Base class for Research endpoints.
         *
         *     ADMIN / OPERATOR / RESEARCHER:
         *         authenticated read access.
         *
         *     WORKER:
         *         denied.
         */
        get: operations["v1_research_h2s_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/h2s-trends/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Base class for Research endpoints.
         *
         *     ADMIN / OPERATOR / RESEARCHER:
         *         authenticated read access.
         *
         *     WORKER:
         *         denied.
         */
        get: operations["v1_research_h2s_trends_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/risk-distribution/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Base class for Research endpoints.
         *
         *     ADMIN / OPERATOR / RESEARCHER:
         *         authenticated read access.
         *
         *     WORKER:
         *         denied.
         */
        get: operations["v1_research_risk_distribution_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_workers_list"];
        put?: never;
        post: operations["v1_workers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_workers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_workers_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ARKLResearchResponse: {
            calculation_version: string;
            count: number;
            results: components["schemas"]["ARKLResearchResult"][];
        };
        ARKLResearchResult: {
            id: number;
            worker_code: string;
            calculation_type: string;
            /** Format: decimal */
            concentration_ppm: string;
            /** Format: decimal */
            concentration_mg_m3: string;
            /** Format: decimal */
            exposure_concentration_mg_m3: string | null;
            /** Format: decimal */
            averaging_time: string | null;
            /** Format: decimal */
            intake: string | null;
            /** Format: decimal */
            rfc: string;
            /** Format: decimal */
            rq: string;
            interpretation: string;
            calculation_version: string;
            source_simulated: boolean;
            reading_id: number | null;
            /** Format: date-time */
            period_start: string | null;
            /** Format: date-time */
            period_end: string | null;
            reading_count: number | null;
            /** Format: date-time */
            created_at: string;
        };
        ARKLResult: {
            readonly id: number;
            readonly worker: number;
            readonly worker_code: string;
            readonly reading: number | null;
            /** Format: date-time */
            readonly reading_received_at: string | null;
            readonly reference_measurement: components["schemas"]["ReferenceMeasurementSnapshot"] | null;
            readonly device_code: string | null;
            readonly calculation_type: components["schemas"]["CalculationTypeEnum"];
            /** @description Status verifikasi profil saat hasil dihitung; null untuk riwayat lama. */
            readonly exposure_profile_verified: boolean | null;
            /** Format: decimal */
            readonly concentration_ppm: string;
            /** Format: decimal */
            readonly concentration_mg_m3: string;
            /** Format: decimal */
            readonly exposure_concentration_mg_m3: string | null;
            /** Format: decimal */
            readonly body_weight: string;
            /** Format: decimal */
            readonly exposure_time: string;
            /** Format: decimal */
            readonly exposure_frequency: string;
            /** Format: decimal */
            readonly exposure_duration: string;
            /** Format: decimal */
            readonly inhalation_rate: string;
            /** Format: decimal */
            readonly averaging_time: string | null;
            /** Format: decimal */
            readonly intake: string | null;
            /** Format: decimal */
            readonly rfc: string;
            /** Format: decimal */
            readonly rq: string;
            readonly interpretation: string;
            readonly calculation_version: string;
            readonly source_simulated: boolean;
            /** Format: date-time */
            readonly period_start: string | null;
            /** Format: date-time */
            readonly period_end: string | null;
            readonly reading_count: number | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        AccountCreate: {
            username: string;
            email?: string;
            password: string;
            role: components["schemas"]["RoleEnum"];
            worker_id?: number | null;
        };
        AccountProfile: {
            readonly id: number;
            readonly username: string;
            /** Format: email */
            readonly email: string;
            readonly role: components["schemas"]["RoleEnum"];
            readonly worker: number | null;
            readonly worker_code: string | null;
            readonly worker_name: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Alert: {
            readonly id: number;
            readonly worker_code: string;
            readonly device_code: string;
            readonly reading_id: number;
            readonly arkl_result_id: number;
            /** Format: decimal */
            readonly concentration_ppm: string;
            readonly environmental_level: number;
            readonly environmental_status: string;
            readonly environmental_severity: components["schemas"]["EnvironmentalSeverityEnum"];
            /** Format: decimal */
            readonly rq: string;
            readonly risk_interpretation: string;
            readonly calculation_version: string;
            readonly alert_level: components["schemas"]["AlertLevelEnum"];
            readonly risk_status: components["schemas"]["RiskStatusEnum"];
            readonly status: components["schemas"]["StatusEnum"];
            readonly recommendation_codes: unknown;
            readonly alert_rule_version: string;
            readonly source_simulated: boolean;
            /** Format: date-time */
            readonly acknowledged_at: string | null;
            readonly acknowledged_by: number | null;
            readonly acknowledged_by_username: string | null;
            /** Format: date-time */
            readonly resolved_at: string | null;
            readonly resolved_by: number | null;
            readonly resolved_by_username: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        AlertEvaluateRequest: {
            arkl_result_id: number;
        };
        AlertEvaluationResponse: {
            created: boolean;
            duplicate: boolean;
            escalated: boolean;
            alert: components["schemas"]["Alert"] | null;
        };
        /**
         * @description * `NONE` - NONE
         *     * `LOW` - LOW
         *     * `MEDIUM` - MEDIUM
         *     * `HIGH` - HIGH
         *     * `CRITICAL` - CRITICAL
         * @enum {string}
         */
        AlertLevelEnum: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        AlertSummary: {
            total_count: number;
            simulated_count: number;
            physical_count: number;
            by_level: components["schemas"]["CountItem"][];
            by_status: components["schemas"]["CountItem"][];
            by_risk_status: components["schemas"]["CountItem"][];
            by_rule_version: components["schemas"]["CountItem"][];
        };
        /**
         * @description * `PENDING` - Menunggu ACC
         *     * `APPROVED` - Disetujui
         *     * `REJECTED` - Perlu perbaikan
         * @enum {string}
         */
        ApprovalStatusEnum: "PENDING" | "APPROVED" | "REJECTED";
        /**
         * @description * `REALTIME` - Realtime
         *     * `HISTORICAL` - Historical
         *     * `REFERENCE` - Sensor referensi
         * @enum {string}
         */
        CalculationTypeEnum: "REALTIME" | "HISTORICAL" | "REFERENCE";
        CountItem: {
            value: string;
            count: number;
        };
        CurrentUser: {
            id: number;
            username: string;
            email: string;
            role: string;
            worker_id: number | null;
            worker_code: string | null;
            worker_name: string | null;
        };
        Device: {
            readonly id: number;
            device_code: string;
            name?: string;
            location?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `NORMAL` - NORMAL
         *     * `CAUTION` - CAUTION
         *     * `WARNING` - WARNING
         *     * `DANGER` - DANGER
         *     * `CRITICAL` - CRITICAL
         * @enum {string}
         */
        EnvironmentalSeverityEnum: "NORMAL" | "CAUTION" | "WARNING" | "DANGER" | "CRITICAL";
        ExposureProfile: {
            readonly id: number;
            worker: number;
            readonly worker_code: string;
            readonly worker_name: string | null;
            /**
             * Format: double
             * @description Berat badan (Wb) dalam kilogram.
             */
            body_weight: number;
            /**
             * Format: double
             * @description Waktu pajanan (tE) dalam jam/hari.
             */
            exposure_time: number;
            /**
             * Format: double
             * @description Frekuensi pajanan (fE) dalam hari/tahun.
             */
            exposure_frequency: number;
            /**
             * Format: double
             * @description Durasi pajanan (Dt) dalam tahun.
             */
            exposure_duration: number;
            /**
             * Format: double
             * @description Laju inhalasi (R) dalam m³/jam. Nilai ditentukan otomatis berdasarkan kategori usia dan metodologi ARKL yang disetujui.
             */
            readonly inhalation_rate: number;
            readonly inhalation_category: string;
            approval_status?: components["schemas"]["ApprovalStatusEnum"];
            review_note?: string;
            /** Format: date-time */
            readonly reviewed_at: string | null;
            readonly reviewed_by: number | null;
            readonly calculation_status: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ExposureSummary: {
            worker_count: number;
            /** Format: double */
            average_body_weight: number | null;
            /** Format: double */
            average_exposure_time: number | null;
            /** Format: double */
            average_exposure_frequency: number | null;
            /** Format: double */
            average_exposure_duration: number | null;
            /** Format: double */
            average_inhalation_rate: number | null;
        };
        H2SReading: {
            readonly id: number;
            readonly device: number;
            readonly device_code: string;
            /** Format: double */
            readonly ppm: number;
            readonly adc: number;
            /** Format: double */
            readonly filtered_adc: number;
            readonly level: number;
            readonly status: string;
            readonly uptime_ms: number;
            readonly simulated: boolean;
            /** Format: date-time */
            readonly received_at: string;
        };
        H2SSummary: {
            sample_count: number;
            /** Format: double */
            minimum_ppm: number | null;
            /** Format: double */
            maximum_ppm: number | null;
            /** Format: double */
            average_ppm: number | null;
            /** Format: date-time */
            first_reading_at: string | null;
            /** Format: date-time */
            last_reading_at: string | null;
            simulated_count: number;
            physical_count: number;
            device_count: number;
        };
        H2STrendResponse: {
            interval: components["schemas"]["IntervalEnum"];
            series: unknown[];
        };
        HistoricalARKLRequest: {
            worker: number;
            device: number;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
        };
        /**
         * @description * `raw` - raw
         *     * `hour` - hour
         *     * `day` - day
         * @enum {string}
         */
        IntervalEnum: "raw" | "hour" | "day";
        Login: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["CurrentUser"];
        };
        /** @description Personal profile: ownership and review fields cannot be supplied by workers. */
        MyExposureProfile: {
            readonly id: number;
            readonly worker_code: string;
            readonly worker_name: string | null;
            /**
             * Format: double
             * @description Berat badan (Wb) dalam kilogram.
             */
            body_weight: number;
            /**
             * Format: double
             * @description Waktu pajanan (tE) dalam jam/hari.
             */
            exposure_time: number;
            /**
             * Format: double
             * @description Frekuensi pajanan (fE) dalam hari/tahun.
             */
            exposure_frequency: number;
            /**
             * Format: double
             * @description Durasi pajanan (Dt) dalam tahun.
             */
            exposure_duration: number;
            /**
             * Format: double
             * @description Laju inhalasi (R) dalam m³/jam. Nilai ditentukan otomatis berdasarkan kategori usia dan metodologi ARKL yang disetujui.
             */
            readonly inhalation_rate: number;
            readonly inhalation_category: string;
            readonly approval_status: components["schemas"]["ApprovalStatusEnum"];
            readonly review_note: string;
            /** Format: date-time */
            readonly reviewed_at: string | null;
            readonly reviewed_by: number | null;
            readonly calculation_status: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        MyMonitoring: {
            readonly device: components["schemas"]["Device"];
            readonly reading: components["schemas"]["H2SReading"] | null;
        };
        MyWorkerProfile: {
            readonly id: number;
            readonly code: string;
            name?: string;
            age?: number;
            readonly is_active: boolean;
            readonly monitoring_device_code: string | null;
            readonly monitoring_device_name: string | null;
            readonly monitoring_device_location: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PaginatedARKLResultList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ARKLResult"][];
        };
        PaginatedAlertList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Alert"][];
        };
        PaginatedDeviceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Device"][];
        };
        PaginatedExposureProfileList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ExposureProfile"][];
        };
        PaginatedH2SReadingList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["H2SReading"][];
        };
        PaginatedReferenceMeasurementList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ReferenceMeasurement"][];
        };
        PaginatedWorkerList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Worker"][];
        };
        PatchedDevice: {
            readonly id?: number;
            device_code?: string;
            name?: string;
            location?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedExposureProfile: {
            readonly id?: number;
            worker?: number;
            readonly worker_code?: string;
            readonly worker_name?: string | null;
            /**
             * Format: double
             * @description Berat badan (Wb) dalam kilogram.
             */
            body_weight?: number;
            /**
             * Format: double
             * @description Waktu pajanan (tE) dalam jam/hari.
             */
            exposure_time?: number;
            /**
             * Format: double
             * @description Frekuensi pajanan (fE) dalam hari/tahun.
             */
            exposure_frequency?: number;
            /**
             * Format: double
             * @description Durasi pajanan (Dt) dalam tahun.
             */
            exposure_duration?: number;
            /**
             * Format: double
             * @description Laju inhalasi (R) dalam m³/jam. Nilai ditentukan otomatis berdasarkan kategori usia dan metodologi ARKL yang disetujui.
             */
            readonly inhalation_rate?: number;
            readonly inhalation_category?: string;
            approval_status?: components["schemas"]["ApprovalStatusEnum"];
            review_note?: string;
            /** Format: date-time */
            readonly reviewed_at?: string | null;
            readonly reviewed_by?: number | null;
            readonly calculation_status?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Personal profile: ownership and review fields cannot be supplied by workers. */
        PatchedMyExposureProfile: {
            readonly id?: number;
            readonly worker_code?: string;
            readonly worker_name?: string | null;
            /**
             * Format: double
             * @description Berat badan (Wb) dalam kilogram.
             */
            body_weight?: number;
            /**
             * Format: double
             * @description Waktu pajanan (tE) dalam jam/hari.
             */
            exposure_time?: number;
            /**
             * Format: double
             * @description Frekuensi pajanan (fE) dalam hari/tahun.
             */
            exposure_frequency?: number;
            /**
             * Format: double
             * @description Durasi pajanan (Dt) dalam tahun.
             */
            exposure_duration?: number;
            /**
             * Format: double
             * @description Laju inhalasi (R) dalam m³/jam. Nilai ditentukan otomatis berdasarkan kategori usia dan metodologi ARKL yang disetujui.
             */
            readonly inhalation_rate?: number;
            readonly inhalation_category?: string;
            readonly approval_status?: components["schemas"]["ApprovalStatusEnum"];
            readonly review_note?: string;
            /** Format: date-time */
            readonly reviewed_at?: string | null;
            readonly reviewed_by?: number | null;
            readonly calculation_status?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedMyWorkerProfile: {
            readonly id?: number;
            readonly code?: string;
            name?: string;
            age?: number;
            readonly is_active?: boolean;
            readonly monitoring_device_code?: string | null;
            readonly monitoring_device_name?: string | null;
            readonly monitoring_device_location?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedReferenceMeasurement: {
            readonly id?: number;
            /** Format: decimal */
            concentration_ppm?: string;
            /** Format: date-time */
            measured_at?: string;
            location?: string;
            source?: string;
            notes?: string;
            workers?: number[];
            /** Format: date-time */
            readonly created_at?: string;
            readonly used?: boolean;
        };
        PatchedWorker: {
            readonly id?: number;
            code?: string;
            name?: string;
            age?: number;
            is_active?: boolean;
            monitoring_device?: number | null;
            readonly monitoring_device_code?: string | null;
            readonly monitoring_device_name?: string | null;
            readonly monitoring_device_location?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        RealtimeARKLRequest: {
            worker: number;
            device: number;
        };
        /**
         * @description Response from one realtime ARKL
         *     orchestration request.
         */
        RealtimeARKLResponse: {
            arkl_result: components["schemas"]["ARKLResult"];
            alert_evaluation: components["schemas"]["AlertEvaluationResponse"];
        };
        ReferenceARKLRequest: {
            worker: number;
            measurement: number;
        };
        ReferenceMeasurement: {
            readonly id: number;
            /** Format: decimal */
            concentration_ppm: string;
            /** Format: date-time */
            measured_at: string;
            location?: string;
            source: string;
            notes?: string;
            workers?: number[];
            /** Format: date-time */
            readonly created_at: string;
            readonly used: boolean;
        };
        /** @description Worker-visible provenance; never expose other assigned worker IDs. */
        ReferenceMeasurementSnapshot: {
            readonly id: number;
            /** Format: decimal */
            readonly concentration_ppm: string;
            /** Format: date-time */
            readonly measured_at: string;
            readonly location: string;
            readonly source: string;
        };
        RiskDistribution: {
            calculation_version: string;
            total_count: number;
            distribution: components["schemas"]["RiskDistributionItem"][];
        };
        RiskDistributionItem: {
            interpretation: string;
            count: number;
            /** Format: double */
            percentage: number;
        };
        /**
         * @description * `NO_ACTION_REQUIRED` - NO_ACTION_REQUIRED
         *     * `MONITORING_REQUIRED` - MONITORING_REQUIRED
         *     * `RISK_MANAGEMENT_REQUIRED` - RISK_MANAGEMENT_REQUIRED
         *     * `IMMEDIATE_ACTION_REQUIRED` - IMMEDIATE_ACTION_REQUIRED
         * @enum {string}
         */
        RiskStatusEnum: "NO_ACTION_REQUIRED" | "MONITORING_REQUIRED" | "RISK_MANAGEMENT_REQUIRED" | "IMMEDIATE_ACTION_REQUIRED";
        /**
         * @description * `ADMIN` - Admin
         *     * `OPERATOR` - Operator
         *     * `RESEARCHER` - Researcher
         *     * `WORKER` - Worker
         * @enum {string}
         */
        RoleEnum: "ADMIN" | "OPERATOR" | "RESEARCHER" | "WORKER";
        /**
         * @description * `OPEN` - OPEN
         *     * `ACKNOWLEDGED` - ACKNOWLEDGED
         *     * `RESOLVED` - RESOLVED
         * @enum {string}
         */
        StatusEnum: "OPEN" | "ACKNOWLEDGED" | "RESOLVED";
        Worker: {
            readonly id: number;
            code: string;
            name: string;
            age: number;
            is_active?: boolean;
            monitoring_device?: number | null;
            readonly monitoring_device_code: string | null;
            readonly monitoring_device_name: string | null;
            readonly monitoring_device_location: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_accounts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["AccountCreate"];
                "multipart/form-data": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountProfile"];
                };
            };
        };
    };
    v1_alerts_list: {
        parameters: {
            query?: {
                alert_level?: string;
                device_code?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                status?: string;
                worker_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAlertList"];
                };
            };
        };
    };
    v1_alerts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    v1_alerts_acknowledge_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    v1_alerts_resolve_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    v1_alerts_evaluate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertEvaluateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AlertEvaluateRequest"];
                "multipart/form-data": components["schemas"]["AlertEvaluateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertEvaluationResponse"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertEvaluationResponse"];
                };
            };
        };
    };
    v1_arkl_historical_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalARKLRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["HistoricalARKLRequest"];
                "multipart/form-data": components["schemas"]["HistoricalARKLRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARKLResult"];
                };
            };
        };
    };
    v1_arkl_realtime_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RealtimeARKLRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RealtimeARKLRequest"];
                "multipart/form-data": components["schemas"]["RealtimeARKLRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeARKLResponse"];
                };
            };
        };
    };
    v1_arkl_reference_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceARKLRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReferenceARKLRequest"];
                "multipart/form-data": components["schemas"]["ReferenceARKLRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARKLResult"];
                };
            };
        };
    };
    v1_arkl_reference_measurements_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReferenceMeasurementList"];
                };
            };
        };
    };
    v1_arkl_reference_measurements_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceMeasurement"];
                "application/x-www-form-urlencoded": components["schemas"]["ReferenceMeasurement"];
                "multipart/form-data": components["schemas"]["ReferenceMeasurement"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceMeasurement"];
                };
            };
        };
    };
    v1_arkl_reference_measurements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceMeasurement"];
                };
            };
        };
    };
    v1_arkl_reference_measurements_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceMeasurement"];
                "application/x-www-form-urlencoded": components["schemas"]["ReferenceMeasurement"];
                "multipart/form-data": components["schemas"]["ReferenceMeasurement"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceMeasurement"];
                };
            };
        };
    };
    v1_arkl_reference_measurements_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedReferenceMeasurement"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedReferenceMeasurement"];
                "multipart/form-data": components["schemas"]["PatchedReferenceMeasurement"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceMeasurement"];
                };
            };
        };
    };
    v1_arkl_results_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedARKLResultList"];
                };
            };
        };
    };
    v1_arkl_results_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARKLResult"];
                };
            };
        };
    };
    v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    v1_devices_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDeviceList"];
                };
            };
        };
    };
    v1_devices_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Device"];
                "application/x-www-form-urlencoded": components["schemas"]["Device"];
                "multipart/form-data": components["schemas"]["Device"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    v1_devices_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this device. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    v1_devices_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this device. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDevice"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDevice"];
                "multipart/form-data": components["schemas"]["PatchedDevice"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    v1_exposure_profiles_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExposureProfileList"];
                };
            };
        };
    };
    v1_exposure_profiles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExposureProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["ExposureProfile"];
                "multipart/form-data": components["schemas"]["ExposureProfile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureProfile"];
                };
            };
        };
    };
    v1_exposure_profiles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exposure profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureProfile"];
                };
            };
        };
    };
    v1_exposure_profiles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exposure profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedExposureProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExposureProfile"];
                "multipart/form-data": components["schemas"]["PatchedExposureProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureProfile"];
                };
            };
        };
    };
    v1_me_alerts_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
        };
    };
    v1_me_arkl_results_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARKLResult"][];
                };
            };
        };
    };
    v1_me_exposure_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyExposureProfile"];
                };
            };
        };
    };
    v1_me_exposure_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MyExposureProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["MyExposureProfile"];
                "multipart/form-data": components["schemas"]["MyExposureProfile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyExposureProfile"];
                };
            };
        };
    };
    v1_me_exposure_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMyExposureProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMyExposureProfile"];
                "multipart/form-data": components["schemas"]["PatchedMyExposureProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyExposureProfile"];
                };
            };
        };
    };
    v1_me_monitoring_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyMonitoring"];
                };
            };
        };
    };
    v1_me_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyWorkerProfile"];
                };
            };
        };
    };
    v1_me_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMyWorkerProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMyWorkerProfile"];
                "multipart/form-data": components["schemas"]["PatchedMyWorkerProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyWorkerProfile"];
                };
            };
        };
    };
    v1_readings_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedH2SReadingList"];
                };
            };
        };
    };
    v1_readings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this h2s reading. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["H2SReading"];
                };
            };
        };
    };
    v1_readings_latest_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["H2SReading"];
                };
            };
        };
    };
    v1_research_alert_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSummary"];
                };
            };
        };
    };
    v1_research_arkl_results_retrieve: {
        parameters: {
            query?: {
                /**
                 * @description * `REALTIME` - REALTIME
                 *     * `HISTORICAL` - HISTORICAL
                 */
                calculation_type?: "REALTIME" | "HISTORICAL";
                calculation_version?: string;
                end?: string;
                source_simulated?: boolean | null;
                start?: string;
                worker_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARKLResearchResponse"];
                };
            };
        };
    };
    "v1_research_export_arkl.csv_retrieve": {
        parameters: {
            query?: {
                /**
                 * @description * `REALTIME` - REALTIME
                 *     * `HISTORICAL` - HISTORICAL
                 */
                calculation_type?: "REALTIME" | "HISTORICAL";
                calculation_version?: string;
                end?: string;
                source_simulated?: boolean | null;
                start?: string;
                worker_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    v1_research_exposure_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureSummary"];
                };
            };
        };
    };
    v1_research_h2s_summary_retrieve: {
        parameters: {
            query?: {
                device_code?: string;
                end?: string;
                source_simulated?: boolean | null;
                start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["H2SSummary"];
                };
            };
        };
    };
    v1_research_h2s_trends_retrieve: {
        parameters: {
            query?: {
                device_code?: string;
                end?: string;
                /**
                 * @description * `raw` - raw
                 *     * `hour` - hour
                 *     * `day` - day
                 */
                interval?: "raw" | "hour" | "day";
                source_simulated?: boolean | null;
                start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["H2STrendResponse"];
                };
            };
        };
    };
    v1_research_risk_distribution_retrieve: {
        parameters: {
            query?: {
                calculation_version?: string;
                source_simulated?: boolean | null;
                worker_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskDistribution"];
                };
            };
        };
    };
    v1_workers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkerList"];
                };
            };
        };
    };
    v1_workers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Worker"];
                "application/x-www-form-urlencoded": components["schemas"]["Worker"];
                "multipart/form-data": components["schemas"]["Worker"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"];
                };
            };
        };
    };
    v1_workers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this worker. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"];
                };
            };
        };
    };
    v1_workers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this worker. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWorker"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWorker"];
                "multipart/form-data": components["schemas"]["PatchedWorker"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"];
                };
            };
        };
    };
}
