# Generated by Django 5.2.17 on 2026-08-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_code",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["device_code"],
            },
        ),
        migrations.CreateModel(
            name="H2SReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ppm", models.FloatField()),
                ("adc", models.PositiveIntegerField()),
                ("filtered_adc", models.FloatField()),
                ("level", models.PositiveSmallIntegerField()),
                ("status", models.CharField(max_length=50)),
                ("uptime_ms", models.PositiveBigIntegerField()),
                ("simulated", models.BooleanField(default=True)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-received_at"], name="h2s_device_time_idx"
                    )
                ],
            },
        ),
    ]
