# Generated by Django 5.2.17 on 2026-08-19 18:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExposureProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_weight",
                    models.FloatField(
                        help_text="Berat badan dalam kilogram.",
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "exposure_time",
                    models.FloatField(
                        help_text="Waktu pajanan. Satuan final mengikuti metode ARKL.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "exposure_frequency",
                    models.FloatField(
                        help_text="Frekuensi pajanan. Satuan final mengikuti metode ARKL.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "exposure_duration",
                    models.FloatField(
                        help_text="Durasi pajanan. Satuan final mengikuti metode ARKL.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "inhalation_rate",
                    models.FloatField(
                        help_text="Laju inhalasi. Satuan final mengikuti metode ARKL.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposure_profile",
                        to="exposure.worker",
                    ),
                ),
            ],
        ),
    ]
