# Generated by Django 5.2.17 on 2026-08-20 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Usia pemulung/responden dalam tahun. Usia bukan parameter langsung rumus ARKL.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, help_text='Nama pemulung/responden.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='exposureprofile',
            name='body_weight',
            field=models.FloatField(help_text='Berat badan (Wb) dalam kilogram.', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='exposureprofile',
            name='exposure_duration',
            field=models.FloatField(help_text='Durasi pajanan (Dt) dalam tahun.', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='exposureprofile',
            name='exposure_frequency',
            field=models.FloatField(help_text='Frekuensi pajanan (fE) dalam hari/tahun.', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='exposureprofile',
            name='exposure_time',
            field=models.FloatField(help_text='Waktu pajanan (tE) dalam jam/hari.', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='exposureprofile',
            name='inhalation_rate',
            field=models.FloatField(help_text='Laju inhalasi (R) dalam m³/jam. Nilai harus mengikuti metodologi ARKL yang disetujui.', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
