# Generated by Django 5.2.17 on 2026-08-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('exposure', '0002_worker_age_worker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='monitoring_device',
            field=models.ForeignKey(blank=True, help_text='Perangkat H2S yang digunakan untuk monitoring lingkungan pemulung.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_workers', to='devices.device'),
        ),
    ]
